import {useMemo,useState} from 'react';import {useNavigate,useParams} from 'react-router-dom';import {ArrowLeft,GitCompare,History,RotateCcw,Undo2} from 'lucide-react';import {PageTitle} from '../components/common';import {useAppStore} from '../store/useAppStore';
export function Versions(){const {id}=useParams(),nav=useNavigate(),store=useAppStore(),w=store.workflows.find(x=>x.id===id)!;const all=[...w.versions].sort((a,b)=>b.version-a.version);const [left,setLeft]=useState(all.at(-1)?.version||1),[right,setRight]=useState(all[0]?.version||w.version),[withdrawing,setWithdrawing]=useState(false),[reason,setReason]=useState('');const a=all.find(v=>v.version===left),b=all.find(v=>v.version===right);const boundCount=(v:number)=>store.instances.filter(i=>i.workflowId===w.id&&i.version===v&&i.status!=='terminated').length;
 const diff=useMemo(()=>{if(!a||!b)return {added:[],removed:[],changed:[]};return {added:b.nodes.filter(n=>!a.nodes.some(x=>x.id===n.id)),removed:a.nodes.filter(n=>!b.nodes.some(x=>x.id===n.id)),changed:b.nodes.filter(n=>{const old=a.nodes.find(x=>x.id===n.id);return old&&JSON.stringify(old.data.config)!==JSON.stringify(n.data.config)})}},[a,b]);
 const restore=()=>{store.setCurrent(w.id);store.restore(left);nav(`/workflows/${w.id}`)};
 const doWithdraw=()=>{store.setCurrent(w.id);store.withdraw(reason.trim()||'操作人未填写原因');setWithdrawing(false);setReason('');nav(`/workflows/${w.id}`)};
 const actionText={upgrade:'切到新版本',retain:'保留旧快照',terminate:'终止实例'} as const;
 return <div className="page versions-page"><button className="back-link" onClick={()=>nav(`/workflows/${id}`)}><ArrowLeft/>返回编辑器</button><PageTitle eyebrow="流程版本" title="Version History" desc={`${w.name} · 发布记录与冻结规则快照，可比较结构差异、撤回版本或恢复历史版本。`}/>
 {w.needDraftReason&&<div className="withdraw-banner" data-testid="withdraw-banner">当前版本已撤回，画布已回退到 v{w.version} 快照；返回编辑器新建带原因的变更草稿后才能继续改动。<button onClick={()=>nav(`/workflows/${w.id}`)}>去处理</button></div>}
 <div className="version-layout"><aside className="panel version-list"><h3><History/>发布记录</h3>{all.map((v,i)=><button key={v.version} className={v.version===right?'active':''} onClick={()=>setRight(v.version)}><span><b>v{v.version}</b>{i===0&&!v.withdrawn&&<em>当前</em>}{v.withdrawn&&<em className="tag-withdrawn">已撤回</em>}</span><small>{v.createdAt}</small><p>{v.note}</p>{v.withdrawn&&v.withdrawReason&&<small className="withdraw-reason">撤回原因：{v.withdrawReason}</small>}<small className="bind-count" data-testid={'bind-count-'+v.version}>绑定实例 {boundCount(v.version)}</small></button>)}{w.status==='published'&&<button className="withdraw-btn" data-testid="withdraw-button" onClick={()=>setWithdrawing(true)}><Undo2/>撤回当前 v{w.version}</button>}</aside>
 <section className="panel compare" data-testid="version-compare"><div className="compare-head"><div><GitCompare/><h2>版本对比</h2></div><button className="secondary" data-testid="restore-version" onClick={restore}><RotateCcw/>恢复 v{left} 为草稿</button></div><div className="compare-select"><label>基准版本<select value={left} onChange={e=>setLeft(Number(e.target.value))}>{all.map(v=><option key={v.version} value={v.version}>v{v.version} · {v.createdAt}</option>)}</select></label><span>→</span><label>比较版本<select value={right} onChange={e=>setRight(Number(e.target.value))}>{all.map(v=><option key={v.version} value={v.version}>v{v.version} · {v.createdAt}</option>)}</select></label></div><div className="diff-summary"><article><small>新增节点</small><b>{diff.added.length}</b></article><article><small>删除节点</small><b>{diff.removed.length}</b></article><article><small>配置变化</small><b>{diff.changed.length}</b></article><article><small>连线变化</small><b>{Math.abs((b?.edges.length||0)-(a?.edges.length||0))}</b></article></div><div className="diff-list"><h3>变更明细</h3>{diff.added.map(n=><div key={n.id} className="diff added"><span>＋ 新增</span><b>{n.data.label}</b><small>{n.type} 节点</small></div>)}{diff.removed.map(n=><div key={n.id} className="diff removed"><span>− 删除</span><b>{n.data.label}</b><small>{n.type} 节点</small></div>)}{diff.changed.map(n=><div key={n.id} className="diff changed"><span>~ 配置</span><b>{n.data.label}</b><small>节点配置已更新</small></div>)}{!diff.added.length&&!diff.removed.length&&!diff.changed.length&&<div className="empty-diff">这两个版本的节点结构一致</div>}<div className="release-note"><small>发布说明</small><p>{b?.note}</p></div></div>
 {b&&<div className="rules-snapshot" data-testid="rules-snapshot"><h3>v{b.version} 冻结规则快照{b.withdrawn&&<span className="tag-withdrawn">已撤回</span>}{boundCount(b.version)>0&&<span className="bind-inline">{boundCount(b.version)} 个实例绑定此版本</span>}</h3>{(b.rules??[]).map(r=><div key={r.nodeId} className="rule-row"><b>{r.nodeLabel}<small>{r.nodeType}</small></b><span>{r.rule}</span></div>)}{b.log&&b.log.length>0&&<div className="release-log"><h4>发布时实例处置</h4>{b.log.map((l,k)=><div key={k} className={'log-row '+l.action}><b>{l.instanceId}</b><span>{actionText[l.action]}</span><small>{l.at}</small></div>)}</div>}</div>}
 </section></div>
 {withdrawing&&<div className="drawer-backdrop"><div className="confirm-dialog" data-testid="withdraw-dialog"><h3>撤回 v{w.version}？</h3><p>撤回后流程立即回到上一发布快照（{all[1]?'v'+all[1].version:'未发布状态'}），已绑定当前版本、保留旧快照或终止的实例不受影响；之后的任何改动都必须新建带原因的变更草稿。</p><label>撤回原因<textarea data-testid="withdraw-reason" rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="例如：发布后发现高额分支阈值配置错误"/></label><div className="dialog-actions"><button className="secondary" onClick={()=>setWithdrawing(false)}>取消</button><button data-testid="withdraw-confirm" disabled={!reason.trim()} onClick={doWithdraw}><Undo2/>确认撤回</button></div></div></div>}
 </div>}
